import { lazy } from 'react'

export const AdminAnalyticsPage = lazy(() => import('./pages/AnalyticsPage'))
export const AdminAuditLogsPage = lazy(() => import('./pages/AuditLogsPage'))
export const AdminCategoriesPage = lazy(() => import('./pages/CategoriesPage'))
export const AdminClientsPage = lazy(() => import('./pages/ClientsPage'))
export const AdminFacebookOrdersPage = lazy(() => import('./pages/FacebookOrdersPage'))
export const AdminInstagramOrdersPage = lazy(() => import('./pages/InstagramOrdersPage'))
export const AdminLoyaltyPage = lazy(() => import('./pages/LoyaltyPage'))
export const AdminModerationPage = lazy(() => import('./pages/ModerationPage'))
export const AdminNewsPage = lazy(() => import('./pages/NewsPage'))
export const AdminNotificationsPage = lazy(() => import('./pages/NotificationsPage'))
export const AdminOrdersPage = lazy(() => import('./pages/OrdersPage'))
export const AdminPricingPage = lazy(() => import('./pages/PricingPage'))
export const AdminProductsPage = lazy(() => import('./pages/ProductsPage'))
export const AdminRevenuePage = lazy(() => import('./pages/RevenuePage'))
export const AdminSettingsPage = lazy(() => import('./pages/SettingsPage'))
export const AdminShipmentTrackingPage = lazy(() => import('./pages/ShipmentTrackingPage'))
export const AdminTestimonialsPage = lazy(() => import('./pages/TestimonialsPage'))
export const AdminWhatsAppOrdersPage = lazy(() => import('./pages/WhatsAppOrdersPage'))
