# Credentials Supabase — NE PAS commiter (dans .gitignore)
# Pooler transaction (port 6543) — depuis Supabase Connect

spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.xslzrmvuehryagrdbklx
spring.datasource.password=Oussama0101010101ouss#

server.port=8081

# Supabase Storage — Project Settings → API → service_role key
supabase.url=https://xslzrmvuehryagrdbklx.supabase.co
supabase.service-key=VOTRE_SERVICE_ROLE_KEY
supabase.storage.bucket=product-images
